version: '3'

services:
  application:
    image: 'filesystem:1.0.0'
    build:
      context: .
    container_name: application
    ports:
      - "8080:8080"
    depends_on:
        database:
            condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/filesystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=filesystem
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL81Dialect

  database:
    image: 'postgres:15.3'
    container_name: database
    environment:
      - POSTGRES_DB=filesystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5